[package]
name = "server"
version = "0.1.0"
edition = "2021"
default-run = "server"

[dependencies]
axum = "0.7.7"
base64 = "0.22.1"
ff = "0.13.0"
hex = "0.4.3"
secp256k1 = { version = "0.30.0", features = ["recovery"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.128"
sha2 = "0.10.8"
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }
radius-circuit = { git = "https://github.com/AntoineF4C5/radius-circuit.git" }
pasta_curves = { version = "0.5", features = ["repr-c", "serde"] }
nova-snark = { git = "https://github.com/argumentcomputer/Nova", branch = "solidity-verifier-pp-spartan" }
bellperson = { version = "0.25", default-features = false }
